version: "3.7"
services:
  api_service:
    build: .
#    restart: always
    ports:
      - "8090:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/proselyte_module_2_5_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      envar.awsaccessKey: "myawsaccessKey"
      envar.awssecretKey: "myawssecretKey"
    depends_on:
      - docker-mysql
    command: sh -c './wait-for mysql_db:3306 -- npm start'
  docker-mysql:
    image: "mysql:8.0"
#    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: proselyte_module_2_5_db
#      MYSQL_USER: root
      MYSQL_PASSWORD: dingo1975
      MYSQL_ROOT_PASSWORD: dingo1975
